# Site settings
title: Siva Krishna Machine Learning
description: A blog about machine learning stuff
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sivakrishna1777.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Siva Krishna Reddy
user_description: Associate Data Scientist and machine learning enthusiast
email: sivakrishnareddy383@gmail.com
twitter_username: lorem_ipsum
github_username:  sivakrishna1777
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: true
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
